<?php

namespace App\Exceptions;

use App\Helpers\Response\ApiResponder;
use Exception;
use BadMethodCallException;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\ItemNotFoundException;
use Illuminate\Validation\ValidationException;
use Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Throwable;
use InvalidArgumentException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;

class CustomException extends ExceptionHandler
{
    public function render($request, Throwable $exception)
    {
        if ($request->is('api/*')) {
            if ($exception instanceof ValidationException) {
                $errors = $exception->errors();
                foreach ($errors as $key => $error) {
                    $myerrors[$key] = $error[0];
                }
                return ApiResponder::get($error[0], $errors, false , 422);
            } elseif ($exception instanceof NotFoundHttpException) {
                return ApiResponder::get('This url not found please check it again', null, false , $exception->getStatusCode());
            } elseif ($exception instanceof MethodNotAllowedHttpException) {
                return ApiResponder::get($exception->getMessage(), null, false , $exception->getStatusCode());
            } elseif ($exception instanceof BadMethodCallException) {
                // return api_response('error', $exception->getMessage(), null, 500);
            } elseif ($exception instanceof AuthenticationException) {
                return ApiResponder::get(__("please login first"), null, false ,401);
            } elseif ($exception instanceof ModelNotFoundException) {
                return ApiResponder::get($exception->getMessage(), null, false , 404);
            } elseif ($exception instanceof InvalidArgumentException) {
                return ApiResponder::get($exception->getMessage(), null, false , 400);
            }elseif ($exception instanceof ItemNotFoundException) {
                return ApiResponder::get($exception->getMessage(), null, false ,  $exception->getStatusCode());
            }
        }
        return parent::render($request, $exception);
    }

    public function report(Throwable $e)
    {
        if ($this->shouldReport($e)) {
            if (config("discord.webhook")) {
                if (config('app.env') == 'local' && env('APP_DEVELOP') == true) {
                    Http::post(
                        config('discord.webhook'),
                        [
                            "content" => 'tls:'.$e->getMessage(),
                        ]
                    );
                }

            }
        }

        return parent::report($e); // TODO: Change the autogenerated stub
    }
}
